### ISSUE TITLE
Is this gem still being maintained?

### ISSUE THREAD

**Issue by FCSadoyama** [splitwise/cacheable#13]
Hello, I've started to develop a gem with the same intent and similar syntax this week. While doing some research I ended up finding this gem and I wanted to know if it is still being maintained

**Comment by rofreg** [comment]
This gem isn't under active development at the moment, but it should work just fine as-is – we've been using it for a while and haven't needed to add any new features! Pull requests are welcome if you'd like to contribute new features or expand upon our existing features 🙂
